name: Deploy and Test

on:
  push:
    branches:
      - automate_pypi_deploy 

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy and Test
        run: |
          cd /home/stefan/expectedparrot/auto-deploy-to-pypi/edsl
          git fetch
          git checkout -f automate_pypi_deploy 
          source ./project/bin/activate
          poetry install
          make bump dev
          make test-data
          make test-serialization
          make publish force=yes
          make bump patch
          make bump dev
          make test-data ARGS=--start_new_version
          git add tests/serialization/data/*
          git commit -m "Update serialization test data after new version bump"
          git push
