name: Publish to Test PyPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      POETRY_VERSION: "1.7.1"
      TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}

      - name: Build and publish to Test PyPI
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ env.TEST_PYPI_TOKEN }}
          make test-pypi
        shell: bash
