name: Python Matrix

on:
  workflow_call:
    outputs:
      matrix:
        description: "The Python version matrix"
        value: ${{ jobs.generate-matrix.outputs.matrix }}

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix=[\"3.13\", \"3.12\", \"3.11\", \"3.10\", \"3.9\"]" >> $GITHUB_OUTPUT